# LED
set_property PACKAGE_PIN M1 [get_ports {led[0]}]
set_property PACKAGE_PIN L1 [get_ports {led[1]}]
set_property PACKAGE_PIN K6 [get_ports {led[2]}]
set_property PACKAGE_PIN J5 [get_ports {led[3]}]
set_property PACKAGE_PIN H5 [get_ports {led[4]}]
set_property PACKAGE_PIN H6 [get_ports {led[5]}]
set_property PACKAGE_PIN K1 [get_ports {led[6]}]
set_property PACKAGE_PIN K2 [get_ports {led[7]}]
set_property PACKAGE_PIN J2 [get_ports {led[8]}]
set_property PACKAGE_PIN J3 [get_ports {led[9]}]
set_property PACKAGE_PIN H4 [get_ports {led[10]}]
set_property PACKAGE_PIN J4 [get_ports {led[11]}]
set_property PACKAGE_PIN G3 [get_ports {led[12]}]
set_property PACKAGE_PIN G4 [get_ports {led[13]}]
set_property PACKAGE_PIN F6 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]

# 输入按键
set_property PACKAGE_PIN R1 [get_ports S]
set_property PACKAGE_PIN R11 [get_ports R]
set_property PACKAGE_PIN V1 [get_ports L]
set_property IOSTANDARD LVCMOS33 [get_ports L]
set_property IOSTANDARD LVCMOS33 [get_ports R]
set_property IOSTANDARD LVCMOS33 [get_ports S]
set_property PACKAGE_PIN R15 [get_ports F1]
set_property PACKAGE_PIN P15 [get_ports F2]
set_property IOSTANDARD LVCMOS33 [get_ports F1]
set_property IOSTANDARD LVCMOS33 [get_ports F2]

# 时钟
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]


# 段选管脚
set_property IOSTANDARD LVCMOS33 [get_ports {tube_L[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_L[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_L[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_L[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_L[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_L[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_L[0]}]
set_property PACKAGE_PIN B2 [get_ports {tube_L[6]}]
set_property PACKAGE_PIN B3 [get_ports {tube_L[5]}]
set_property PACKAGE_PIN A1 [get_ports {tube_L[4]}]
set_property PACKAGE_PIN B1 [get_ports {tube_L[3]}]
set_property PACKAGE_PIN A3 [get_ports {tube_L[2]}]
set_property PACKAGE_PIN A4 [get_ports {tube_L[1]}]
set_property PACKAGE_PIN B4 [get_ports {tube_L[0]}]
set_property PACKAGE_PIN D2 [get_ports {tube_R[6]}]
set_property PACKAGE_PIN E2 [get_ports {tube_R[5]}]
set_property PACKAGE_PIN F3 [get_ports {tube_R[4]}]
set_property PACKAGE_PIN F4 [get_ports {tube_R[3]}]
set_property PACKAGE_PIN D3 [get_ports {tube_R[2]}]
set_property PACKAGE_PIN E3 [get_ports {tube_R[1]}]
set_property PACKAGE_PIN D4 [get_ports {tube_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_R[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_R[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_R[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_R[0]}]

# 片选引脚
set_property PACKAGE_PIN H1 [get_ports k_L]
set_property PACKAGE_PIN G6 [get_ports k_R]
set_property IOSTANDARD LVCMOS33 [get_ports k_L]
set_property IOSTANDARD LVCMOS33 [get_ports k_R]